### ISSUE TITLE
Recipe Cobblegen

### ISSUE THREAD

**Issue by pansjke** [Team-Rapture/Modpack-Hypothermia#17]
I'm unable to see the recipe for the cobblestone gen tier 1 in 1.4c

**Comment by CDArena** [comment]
It is still missing in 1.4d

It is removed via minetweaker script, so it is probably intentional - having said that I have no idea why the author didn't remove the other Tier cobblegens - it is confusing to see items in JEI with no recipe listed. Manual cobble gen works, as does adding an item transfer node with mining upgrade (as long as you have a block of cobble with water source on one side, and lava source on the other).

If you want to add it back in to your pack, find your instance of Hypothermia on your hard drive, and go into the Scripts folder. Edit the MineTweakerRecipeMaker.zs file (I use the Notepad++ editor - a free download) and comment out or delete line 43 which says "recipes.remove(<tp:cobblegen_block>);"

Comments are made by adding two slashes at the beginning of a line. Save the file, restart Hypothermia and viola!

**Comment by Traverse-Joe** [comment]
it's removed so my oredict version overrides but yes u can turn it on, Idk why ppl say it doesn't work, the public server has it and my 14 fresh instances had it I will remove the overrider til then please do as the above states 1.4d will be the last til the big 1.5 update
